trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Continuous_Integration
  displayName: Build
  jobs:
  - job: Build
    steps:
      - task: Maven@3
        displayName: 'Maven Deploy artifact'
        inputs:
          mavenPomFile: 'gateway/pom.xml'
          goals: 'deploy'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          codeCoverageToolOption: 'JaCoCo'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: true
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          checkStyleRunAnalysis: true
          pmdRunAnalysis: true

      - task: CopyFiles@2
        displayName: 'Copy File to Artifact Staging Directory'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact as Drop'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'